Remove ref. to network object in examples
EpiModel/EpiModel-Gallery pull request #29
Opened 2020-11-03 15:45 UTC by andsv2

Closes #27. Work in progress.

2020-11-05 16:21 UTC, andsv2 commented
@smjenness 
All references to the network object have been removed, except where it is called within bespoke initialization modules. All scripts are currently passing on TRAVIS.

2020-11-05 16:59 UTC, smjenness commented
> @smjenness
> All references to the network object have been removed, except where it is called within bespoke initialization modules. All scripts are currently passing on TRAVIS.

It is necessary to resolve the three conflicting files below first, and then you can click the "ready for review" button.

2020-11-05 16:59 UTC, smjenness requested changes
Fix merge conflicts

2020-11-06 12:41 UTC, smjenness approved these changes

2020-11-06 12:41 UTC, merged